### PR TITLE
change to new ui and add endpoints

### PR DESCRIPTION
**Pull request by JamieScottC**
## Description

This PR updates the UI to alpine. Additionally, the old UI accessed the adversaries and abilities by serving them with jinja templating. This PR exposes two new endpoints, `/plugin/response/adversaries` and `/plugin/response/abilities` and they are fetched on the front-end. If this isn't desirable I can remove the endpoints and continue to serve the adversaries/abilities with the template. Finally, I added a toast when the user successfully saves a response.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Compared the new UI and old UI to make sure they look the same and have the same functionality. Saved multiple responses with no trouble.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by elegantmoose — APPROVED** [review]
LGTM

@clenk Do you want to do a once over

**Review by elegantmoose — DISMISSED** [review]

**Review by clenk — COMMENTED** [review]
The UI doesn't seem to reflect the selected defender adversary from the config. `conf/response.yml`. It's set to `7e422753-ad7a-4401-bc8b-b12a28e69c25` which is "Incident Responder", but in the UI the "Query Sysmon" defender is selected on load.

I'm fine with using new API endpoints as that's how stockpile does it now, too. However because of that change we don't need most of the contents of `splash()` in the response_svc since it was mainly populating the data for the jinja template. We may still need the `await self.apply_adversary_config()` call though.

**Comment by JamieScottC** [comment]
> The UI doesn't seem to reflect the selected defender adversary from the config. In `conf/response.yml` it's set to `7e422753-ad7a-4401-bc8b-b12a28e69c25` which is "Incident Responder", but in the UI the "Query Sysmon" defender is selected on load.

Good catch. The selected adversary should now correspond with the correct ID in the `conf/response.yml` file. Instead of making another endpoint for `auto_response` I just continued to serve it through jinja templating.
https://github.com/mitre/response/blob/af51ad6a213a22f4f3d847da9f38416290c3a4f9/templates/response.html#L50

> I'm fine with using new API endpoints as that's how stockpile does it now, too. However because of that change we don't need most of the contents of `splash()` in the response_svc since it was mainly populating the data for the jinja template. We may still need the `await self.apply_adversary_config()` call though.

Got it. I removed all the unnecessary data from `splash()`.
https://github.com/mitre/response/blob/af51ad6a213a22f4f3d847da9f38416290c3a4f9/app/response_svc.py#L55-L57

**Review by clenk — APPROVED** [review]
LGTM; thanks @JamieScottC!

**Pull request merged**
